import { expect, test, type Page } from '@playwright/test'

async function openComponent(page: Page, tag: string) {
  await page.goto('/')
  const toggle = page.getByRole('button', { name: '打开组件导航', exact: true })
  if (await toggle.isVisible()) await toggle.click()
  await page.getByRole('searchbox', { name: '搜索组件' }).fill(tag)
  if (await toggle.isVisible()) await toggle.click()
  await page.locator('.catalog-item').filter({ has: page.getByText(tag, { exact: true }) }).click()
  await expect(page.locator('.detail-footer')).toContainText(`<${tag} />`)
  await expect(page.locator('.gallery-page')).toHaveCount(1)
}

test('segmented selection moves one persistent background instead of crossfading items', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await openComponent(page, 'apple-segmented-control')
  const group = page.locator('.component-demo .apple-segmented')
  const indicator = group.locator('.apple-selection-indicator')
  await expect(indicator).toBeVisible()
  const initial = await indicator.boundingBox()
  await group.getByText('日', { exact: true }).hover()
  await page.mouse.down()
  await expect(group.locator('.v-ripple__container')).toHaveCount(0)
  await page.mouse.up()
  await group.getByText('日', { exact: true }).click()
  await expect.poll(async () => (await indicator.boundingBox())!.x).toBeLessThan(initial!.x - 50)
  await expect(indicator).toHaveCount(1)
  const visual = await indicator.evaluate(element => ({ opacity: getComputedStyle(element).opacity, property: getComputedStyle(element).transitionProperty, duration: getComputedStyle(element).transitionDuration }))
  expect(visual.opacity).toBe('1')
  expect(visual.property).toContain('transform')
  expect(parseFloat(visual.duration)).toBeGreaterThan(0)
  expect(await group.locator('[data-apple-selected=true]').evaluate(element => getComputedStyle(element).backgroundColor)).toBe('rgba(0, 0, 0, 0)')
})

for (const width of [1440, 320]) {
  test(`custom select and cascader use translucent blur and real selectable options at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await openComponent(page, 'apple-select')
    const combo = page.locator('.component-demo').getByRole('combobox')
    await combo.click()
    const menu = page.locator('.component-demo .apple-field-menu')
    await expect(menu).toBeVisible()
    const styles = await menu.evaluate(element => ({ blur: getComputedStyle(element).backdropFilter, background: getComputedStyle(element).backgroundColor }))
    expect(styles.blur).toContain('blur(')
    expect(styles.background).toMatch(/0\.78|78%/)
    expect(await page.locator('.component-demo select').count()).toBe(0)
    await page.getByRole('option', { name: '上海', exact: true }).click()
    await expect(combo).toContainText('上海')
    await expect(menu).toHaveCount(0)
    await openComponent(page, 'apple-cascader')
    await page.locator('.component-demo').getByRole('combobox').click()
    await page.getByRole('option', { name: '浙江省', exact: true }).click()
    const cascader = page.locator('.component-demo')
    await expect(cascader.getByRole('combobox')).toHaveCount(2)
    await cascader.getByRole('combobox').nth(1).click()
    await page.getByRole('option', { name: '杭州市', exact: true }).click()
    await expect(cascader.getByRole('combobox')).toHaveCount(3)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
}

test('autocomplete resizes the result menu with a height animation and exits by collapsing', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await openComponent(page, 'apple-autocomplete')
  const combo = page.locator('.component-demo').getByRole('combobox')
  await combo.focus()
  const menu = page.locator('.component-demo .apple-field-menu')
  await expect(menu.getByRole('option')).toHaveCount(3)
  await expect.poll(async () => Math.round((await menu.boundingBox())!.height)).toBeGreaterThan(130)
  await combo.fill('MacBook')
  await expect(menu.getByRole('option')).toHaveCount(1)
  const animations = await menu.evaluate(element => element.getAnimations({ subtree: true }).map(animation => (animation.effect as KeyframeEffect).getKeyframes()))
  expect(animations.flat().some(frame => 'height' in frame)).toBe(true)
  await expect.poll(async () => Math.round((await menu.boundingBox())!.height)).toBeLessThan(90)
  await combo.press('Escape')
  await expect(menu).toHaveCount(0)
})

test('date segments clamp without focus advance, show the time tab, and exclude only the real selected date from hover trails', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await openComponent(page, 'apple-date-picker')
  const date = page.locator('.apple-date-field')
  const year = date.locator('[data-part=year]')
  await year.fill('999999')
  await expect(year).toHaveValue('9999')
  await expect(year).toBeFocused()
  await year.fill('2026')
  await date.locator('[data-part=month]').fill('99')
  await expect(date.locator('[data-part=month]')).toHaveValue('12')
  await expect(date.locator('[data-part=month]')).toBeFocused()
  await date.locator('[data-part=month]').fill('09')
  await date.locator('[data-part=day]').fill('26')
  await date.locator('[data-part=hour]').fill('12')
  await date.locator('[data-part=minute]').fill('30')
  await date.getByRole('button', { name: '打开日历', exact: true }).click()
  const selected = date.locator('[data-date="2026-09-26"]')
  await expect(selected).toHaveClass(/is-selected/)
  await selected.hover()
  await date.locator('[data-date="2026-09-25"]').hover()
  expect(await selected.evaluate(element => element.getAnimations().some(animation => (animation.effect as KeyframeEffect).getKeyframes().some(frame => 'backgroundColor' in frame)))).toBe(false)
  await date.locator('.apple-calendar__heading').click()
  await date.locator('.apple-calendar__heading').click()
  await date.getByRole('button', { name: '2027', exact: true }).click()
  await date.getByRole('button', { name: '9月', exact: true }).click()
  const otherYear = date.locator('[data-date="2027-09-26"]')
  await expect(otherYear).not.toHaveClass(/is-selected/)
  await otherYear.hover()
  await date.locator('[data-date="2027-09-25"]').hover()
  expect(await otherYear.evaluate(element => element.getAnimations().some(animation => (animation.effect as KeyframeEffect).getKeyframes().some(frame => 'backgroundColor' in frame)))).toBe(true)
  await otherYear.click()
  await expect(date.getByRole('tab', { name: '时间', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(date.locator('.apple-calendar__time-column')).toHaveCount(2)
  await expect.poll(() => date.locator('.apple-date-menu').evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
  await page.screenshot({ path: 'artifacts/date-picker-desktop.png', fullPage: true, animations: 'disabled' })
})

test('mobile calendar stays in bounds and supports time-only precision', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 900 })
  await openComponent(page, 'apple-date-picker')
  const date = page.locator('.apple-date-field')
  await date.getByRole('button', { name: '打开日历', exact: true }).click()
  await expect(date.locator('.apple-date-menu')).toBeVisible()
  await expect.poll(async () => (await date.locator('.apple-date-menu').boundingBox())!.height).toBeGreaterThan(350)
  await expect.poll(() => date.locator('.apple-date-menu').evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
  const bounds = await date.locator('.apple-date-menu').boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320)
  await page.screenshot({ path: 'artifacts/date-picker-mobile.png', fullPage: true, animations: 'disabled' })
  await date.getByRole('button', { name: '完成', exact: true }).click()
  await page.getByRole('combobox', { name: '日期精度', exact: true }).click()
  await page.getByRole('option', { name: '时分秒', exact: true }).click()
  await date.getByRole('button', { name: '选择时间', exact: true }).click()
  await expect(date.locator('.apple-calendar__time-column')).toHaveCount(3)
  await expect(date.locator('.apple-calendar__days')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
