import { activeCard, openComponent } from './component-navigation'
import { expect, test, type Page } from '@playwright/test'



test('segmented selection moves one persistent background instead of crossfading items', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await openComponent(page, 'apple-segmented-control')
  const group = activeCard(page).locator('.component-demo .apple-segmented')
  const indicator = group.locator('.apple-selection-indicator')
  await expect(indicator).toBeVisible()
  const initial = await indicator.boundingBox()
  await group.getByText('日', { exact: true }).hover()
  await page.mouse.down()
  await expect(group.locator('.v-ripple__container')).toHaveCount(0)
  await page.mouse.up()
  await group.getByText('日', { exact: true }).click()
  await expect.poll(async () => (await indicator.boundingBox())!.x).toBeLessThan(initial!.x - 50)
  await expect(indicator).toHaveCount(1)
  const visual = await indicator.evaluate(element => ({ opacity: getComputedStyle(element).opacity, property: getComputedStyle(element).transitionProperty, duration: getComputedStyle(element).transitionDuration }))
  expect(visual.opacity).toBe('1')
  expect(visual.property).toContain('transform')
  expect(parseFloat(visual.duration)).toBeGreaterThan(0)
  expect(await group.locator('[data-apple-selected=true]').evaluate(element => getComputedStyle(element).backgroundColor)).toBe('rgba(0, 0, 0, 0)')
})

test('dark segmented separates the card, track and sampled B selection and follows global motion', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/settings')
  await page.getByRole('button', { name: '深色', exact: true }).click()
  await page.getByRole('radiogroup', { name: '全局动效', exact: true }).getByText('完整', { exact: true }).click()
  await openComponent(page, 'apple-transition')
  const group = activeCard(page).locator('.component-demo .apple-segmented')
  const indicator = group.locator('.apple-selection-indicator')
  await page.mouse.move(0, 0)
  await expect(group).toHaveAttribute('data-apple-scheme', 'dark')
  await expect(activeCard(page)).toHaveCSS('background-color', 'rgb(34, 34, 36)')
  await expect(group).toHaveCSS('background-color', 'rgb(54, 54, 58)')
  await expect(group).toHaveCSS('border-width', '0px')
  await expect(indicator).toHaveCSS('background-color', 'rgb(81, 80, 85)')
  await expect(group.locator('.is-selected')).toHaveCSS('color', 'rgb(245, 244, 245)')
  await expect(group.locator('.apple-segmented__item:not(.is-selected)').first()).toHaveCSS('color', 'rgb(166, 165, 169)')
  const x = (await indicator.boundingBox())!.x
  await group.getByText('日', { exact: true }).click()
  await expect.poll(async () => (await indicator.boundingBox())!.x).toBeLessThan(x - 50)
  await expect(indicator).toHaveCount(1)
  expect(await indicator.evaluate(el => parseFloat(getComputedStyle(el).transitionDuration))).toBeGreaterThan(0)
  await page.mouse.move(0, 0)
  await expect(group.locator('.is-selected')).toHaveCSS('color', 'rgb(245, 244, 245)')
  await page.screenshot({ path: '/tmp/apptify-forms-task/dark-segmented-lighter-track-B.png' })
  await page.goto('/settings')
  await page.getByRole('radiogroup', { name: '全局动效', exact: true }).getByText('关闭', { exact: true }).click()
  await openComponent(page, 'apple-transition')
  await group.getByText('周', { exact: true }).click()
  await expect(group.locator('.is-selected')).toContainText('周')
  await expect(indicator).toHaveCSS('transition-duration', '0s')
})

for (const width of [1440, 320]) {
  test(`custom select and cascader use translucent blur and real selectable options at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await openComponent(page, 'apple-select')
    const combo = activeCard(page).locator('.component-demo').getByRole('combobox')
    await combo.click()
    const menu = activeCard(page).locator('.component-demo .apple-field-menu')
    await expect(menu).toBeVisible()
    const styles = await menu.evaluate(element => ({ blur: getComputedStyle(element).backdropFilter, background: getComputedStyle(element).backgroundColor }))
    expect(styles.blur).toBe('blur(12px) saturate(2)')
    expect(styles.background).toBe('rgba(255, 255, 255, 0.5)')
    expect(await activeCard(page).locator('.component-demo select').count()).toBe(0)
    await page.getByRole('option', { name: '上海', exact: true }).click()
    await expect(combo).toContainText('上海')
    await expect(menu).toHaveCount(0)
    await combo.click()
    await page.mouse.move(0, 0)
    const selected = page.getByRole('option', { name: '上海', exact: true })
    await expect(selected).toHaveAttribute('aria-selected', 'true')
    await expect(selected).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(selected.locator('svg')).toBeVisible()
    await page.getByRole('option', { name: '北京', exact: true }).hover()
    await expect(page.getByRole('option', { name: '北京', exact: true })).toHaveCSS('background-color', 'rgba(128, 128, 128, 0.08)')
    await expect(page.getByRole('option', { name: '北京', exact: true })).toHaveCSS('outline-style', 'none')
    await combo.press('End')
    await expect(combo).toHaveAttribute('aria-activedescendant', /option-2$/)
    await expect(page.getByRole('option', { name: '杭州', exact: true })).toHaveCSS('outline-style', 'solid')
    await combo.press('Escape')
    await openComponent(page, 'apple-cascader')
    await activeCard(page).locator('.component-demo').getByRole('combobox').click()
    await page.getByRole('option', { name: '浙江省', exact: true }).click()
    const cascader = activeCard(page).locator('.component-demo')
    await expect(cascader.getByRole('combobox')).toHaveCount(2)
    await cascader.getByRole('combobox').nth(1).click()
    await page.getByRole('option', { name: '杭州市', exact: true }).click()
    await expect(cascader.getByRole('combobox')).toHaveCount(3)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
}

test('autocomplete resizes the result menu with a height animation and exits by collapsing', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await openComponent(page, 'apple-autocomplete')
  const combo = activeCard(page).locator('.component-demo').getByRole('combobox')
  await combo.focus()
  const menu = activeCard(page).locator('.component-demo .apple-field-menu')
  await expect(menu.getByRole('option')).toHaveCount(3)
  await expect.poll(async () => Math.round((await menu.boundingBox())!.height)).toBeGreaterThan(130)
  await expect.poll(() => menu.evaluate(el => el.getAnimations({ subtree: true }).length)).toBe(0)
  const resized = await combo.evaluate(async element => {
    const input = element as HTMLInputElement
    const menu = input.closest('.apple-autocomplete')!.querySelector('.apple-field-menu')!
    input.value = 'MacBook'
    input.dispatchEvent(new Event('input', { bubbles: true }))
    for (let frame = 0; frame < 12; frame++) {
      await new Promise(requestAnimationFrame)
      if (menu.getAnimations({ subtree: true }).some(animation => (animation.effect as KeyframeEffect).getKeyframes().some(frame => 'height' in frame))) return true
    }
    return false
  })
  await expect(menu.getByRole('option')).toHaveCount(1)
  expect(resized).toBe(true)
  await expect.poll(async () => Math.round((await menu.boundingBox())!.height)).toBeLessThan(90)
  await combo.press('Escape')
  await expect(menu).toHaveCount(0)
})

test('date segments clamp without focus advance, show the time tab, and exclude only the real selected date from hover trails', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await openComponent(page, 'apple-date-picker')
  const date = page.locator('.apple-date-field')
  const year = date.locator('[data-part=year]')
  await year.fill('999999')
  await expect(year).toHaveValue('9999')
  await expect(year).toBeFocused()
  await year.fill('2026')
  await date.locator('[data-part=month]').fill('99')
  await expect(date.locator('[data-part=month]')).toHaveValue('12')
  await expect(date.locator('[data-part=month]')).toBeFocused()
  await date.locator('[data-part=month]').fill('09')
  await date.locator('[data-part=day]').fill('26')
  await date.locator('[data-part=hour]').fill('12')
  await date.locator('[data-part=minute]').fill('30')
  await date.getByRole('button', { name: '打开日历', exact: true }).click()
  const selected = date.locator('[data-date="2026-09-26"]')
  await expect(selected).toHaveClass(/is-selected/)
  await selected.hover()
  await date.locator('[data-date="2026-09-25"]').hover()
  expect(await selected.evaluate(element => element.getAnimations().some(animation => (animation.effect as KeyframeEffect).getKeyframes().some(frame => 'backgroundColor' in frame)))).toBe(false)
  await date.locator('.apple-calendar__heading').click()
  await date.locator('.apple-calendar__heading').click()
  // These pointer checks target settled pages. Rapid in-flight reversals are
  // sampled separately in date-depth.spec.ts without scrolling incoming cells.
  const waitForPage = () => expect.poll(() => date.locator('.apple-calendar__viewport').evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
  await waitForPage()
  await date.getByRole('button', { name: '2027', exact: true }).click()
  await waitForPage()
  await date.getByRole('button', { name: '9月', exact: true }).click()
  await waitForPage()
  const otherYear = date.locator('[data-date="2027-09-26"]')
  await expect(otherYear).not.toHaveClass(/is-selected/)
  await otherYear.hover()
  await date.locator('[data-date="2027-09-25"]').hover()
  const hoverTrailFrames = await otherYear.evaluate(element => element.getAnimations().flatMap(animation => (animation.effect as KeyframeEffect).getKeyframes()).filter(frame => 'backgroundColor' in frame))
  expect(hoverTrailFrames.some(frame => frame.backgroundColor === 'rgba(128, 128, 128, 0.08)')).toBe(true)
  await otherYear.click()
  await expect(date.getByRole('tab', { name: '时间', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(date.locator('.apple-calendar__time-column')).toHaveCount(2)
  await expect.poll(() => date.locator('.apple-date-menu').evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
  await page.screenshot({ path: '/tmp/apptify-checks/date-picker-desktop.png', fullPage: false, animations: 'disabled' })
})

test('mobile calendar stays in bounds and supports time-only precision', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 900 })
  await openComponent(page, 'apple-date-picker')
  const date = page.locator('.apple-date-field')
  await date.getByRole('button', { name: '打开日历', exact: true }).click()
  await expect(date.locator('.apple-date-menu')).toBeVisible()
  await expect.poll(async () => (await date.locator('.apple-date-menu').boundingBox())!.height).toBeGreaterThan(350)
  await expect.poll(() => date.locator('.apple-date-menu').evaluate(element => element.getAnimations({ subtree: true }).length)).toBe(0)
  const bounds = await date.locator('.apple-date-menu').boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320)
  await page.screenshot({ path: '/tmp/apptify-checks/date-picker-mobile.png', fullPage: false, animations: 'disabled' })
  await date.getByRole('button', { name: '完成', exact: true }).click()
  await page.getByRole('combobox', { name: '日期精度', exact: true }).click()
  await page.getByRole('option', { name: '时分秒', exact: true }).click()
  await date.getByRole('button', { name: '选择时间', exact: true }).click()
  await expect(date.locator('.apple-calendar__time-column')).toHaveCount(3)
  await expect(date.locator('.apple-calendar__days')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
