import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => { await page.goto('/tests/e2e/fixtures/image-carousel.html') })

test('carousel mode shares the image controls, labels and selected-slide focus boundary', async ({ page }) => {
  const cards = page.getByRole('region', { name: '计划轮播', exact: true })
  await expect(cards).toHaveAttribute('data-gallery-layout', 'compact')
  await expect(cards).toHaveAttribute('aria-roledescription', '轮播图')
  await expect(cards.getByRole('button', { name: '选择第一项', exact: true })).toBeVisible()
  await expect(cards.getByRole('button', { name: '选择第二项', exact: true })).toHaveCount(0)
  await cards.getByRole('button', { name: '下一张图片', exact: true }).click()
  await expect(cards).toHaveAttribute('data-index', '1')
  await expect(cards.getByRole('button', { name: '选择第二项', exact: true })).toBeVisible()
  await expect(cards.getByRole('button', { name: '选择第一项', exact: true })).toHaveCount(0)
  await cards.getByRole('button', { name: '选择第二项', exact: true }).click()
  await expect(page.locator('#selected')).toHaveText('1')
  const track = cards.locator('.apple-image__gallery')
  await track.focus()
  await page.keyboard.press('ArrowRight')
  await expect(cards).toHaveAttribute('data-index', '2')
  await expect(cards.getByRole('button', { name: '下一张图片', exact: true })).toBeDisabled()
  await cards.getByRole('button', { name: '查看第一项', exact: true }).click()
  await expect(cards).toHaveAttribute('data-index', '0')
})

test('external index, disabled controls and dynamic gallery share one state', async ({ page }) => {
  const cards = page.locator('#cards')
  await page.locator('#set-index').click()
  await expect(cards).toHaveAttribute('data-index', '2')
  await page.locator('#disable').click()
  await expect(cards.locator('.apple-image__gallery')).toHaveAttribute('tabindex', '-1')
  await expect(cards.getByRole('button', { name: '上一张图片', exact: true })).toBeDisabled()
  await expect(cards.getByRole('button', { name: '查看第一项', exact: true })).toBeDisabled()
  await cards.locator('.apple-image__gallery').dispatchEvent('keydown', { key: 'ArrowLeft' })
  await expect(cards).toHaveAttribute('data-index', '2')
  await page.locator('#disable').click()
  await page.locator('#short').click()
  await expect(cards).toHaveAttribute('data-index', '0')
  await expect(cards.locator('.apple-image__slide')).toHaveCount(1)
  await expect(cards.getByRole('button', { name: '选择第一项', exact: true })).toBeVisible()
})

test('carousel default photos preserve preview opening and reduced motion behavior', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const photos = page.locator('#photos')
  await expect(photos).toHaveAttribute('data-apple-motion', 'reduced')
  await expect(photos.locator('.apple-image__slide-caption').first()).toContainText('山间清晨')
  await photos.getByRole('button', { name: '查看一场聆听', exact: true }).click()
  await expect(photos).toHaveAttribute('data-index', '1')
  await photos.getByRole('button', { name: '放大图片：一场聆听', exact: true }).click()
  const viewer = page.getByRole('dialog', { name: '图片预览', exact: true })
  await expect(viewer).toBeVisible()
  await expect(viewer.locator('.apple-viewer-count')).toHaveText('2 / 4')
  await page.keyboard.press('Escape')
  await expect(viewer).toHaveCount(0)
  await expect(photos).toHaveAttribute('data-index', '1')
})

for (const width of [320, 1440]) {
  test(`carousel controls remain visible without hover at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 })
    const photos = page.locator('#photos')
    await expect(photos.locator('.apple-image__arrows')).toHaveCSS('opacity', '1')
    await expect(photos.getByRole('button', { name: '下一张图片', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await photos.getByRole('button', { name: '下一张图片', exact: true }).click()
    await expect(photos).toHaveAttribute('data-index', '1')
  })
}
