import { test, expect } from '@playwright/test'
import { mkdir, writeFile } from 'node:fs/promises'
const artifacts = 'test-results/input-workshop'
test('dedicated API page uses library accordions, lazy reusable editor and responsive layout', async ({ page }) => {
  test.setTimeout(90000)
  await mkdir(artifacts, { recursive: true })
  const errors: string[] = [], resources: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  page.on('response', r => { if (/LiveVueEditor|assets\/editor\/|repl|codemirror/.test(r.url())) resources.push(r.url()) })
  await page.goto('/components#apple-input')
  const entryLink = page.locator('#apple-input .documentation-entry .apple-link')
  await expect(entryLink).toHaveText('代码与 API')
  await expect(page.locator('#apple-input .component-source')).toHaveCount(0)
  const footerStyles = await page.evaluate(() => {
    const link = window.document.querySelector('#apple-input .documentation-entry .apple-link')!
    const comparison = window.document.querySelector('#apple-textarea .component-source button')!
    const read = (el: Element) => { const s = getComputedStyle(el); return { padding: s.padding, fontSize: s.fontSize, fontWeight: s.fontWeight, color: s.color, height: el.getBoundingClientRect().height } }
    return { link: read(link), comparison: read(comparison) }
  })
  expect(footerStyles.link).toEqual(footerStyles.comparison)
  await entryLink.scrollIntoViewIfNeeded()
  await page.screenshot({ path: artifacts + '/entry-aligned.png' })
  await entryLink.click()
  await expect(page).toHaveURL(/\/component-docs\/apple-input$/)
  await expect(page.getByRole('heading', { name: '输入框 AppleInput' })).toBeVisible()
  const document = page.getByTestId('component-document')
  await expect(document.getByRole('tab')).toHaveCount(0)
  await expect(page.getByRole('navigation', { name: '组件文档路径' })).toBeVisible()
  await expect(page.locator('.documentation-page')).toHaveCSS('padding', '40px')
  await page.waitForFunction(() => !window.document.getAnimations().some(a => a.playState === 'running' && Number.isFinite(Number(a.effect?.getComputedTiming().endTime))))
  await page.screenshot({ path: artifacts + '/page-heading.png' })
  await expect(document.locator('.api-entry')).toHaveCount(17)
  await expect(document.locator('.apple-accordion')).toHaveCount(15)
  await expect(document.locator('[data-api="prop-model-value"] .apple-accordion')).toHaveCount(0)
  await expect(document.locator('[data-api="prop-placeholder"] .apple-accordion')).toHaveCount(0)
  await expect(page.locator('.CodeMirror, .vue-repl iframe')).toHaveCount(0)
  expect(resources).toEqual([])
  await expect(document.locator('.example-introduction')).toHaveCount(0)
  const tree = page.getByRole('tree', { name: '组件 API 树' })
  await expect(tree.locator('[role="treeitem"][aria-level="2"]')).toHaveCount(17)
  const clearNode = tree.getByRole('treeitem', { name: 'clearable', exact: true })
  await clearNode.click()
  await expect(page).toHaveURL(/#prop-clearable$/)
  await expect(clearNode).toHaveAttribute('aria-selected', 'true')
  await expect(document.locator('[data-api="prop-clearable"]')).toBeInViewport()
  const eventGroup = tree.getByRole('treeitem', { name: '事件', exact: true })
  await eventGroup.focus()
  await eventGroup.press('ArrowLeft')
  await expect(eventGroup).toHaveAttribute('aria-expanded', 'false')
  await eventGroup.press('ArrowRight')
  await expect(eventGroup).toHaveAttribute('aria-expanded', 'true')
  await expect(tree.locator('[role="treeitem"][aria-level="2"]')).toHaveCount(17)
  const stats = () => page.evaluate(() => ({ dom: window.document.querySelectorAll('*').length, iframes: window.document.querySelectorAll('.vue-repl iframe').length, editors: window.document.querySelectorAll('.CodeMirror').length }))
  const before = await stats()
  const code = page.locator('.CodeMirror'), frame = page.frameLocator('.vue-repl iframe')
  const apiChecks = [
    ['prop-type', '内容'], ['prop-clearable', '内容'], ['prop-label', '姓名'],
    ['prop-hint', '显示名称'], ['prop-error', '姓名'], ['prop-disabled', '密码'],
    ['prop-loading', '名称'], ['prop-required', '姓名'], ['prop-motion', '内容'],
    ['event-update-model-value', '数量'], ['event-change', '姓名'], ['event-clear', '内容'],
    ['slot-prefix', '用户名'], ['slot-suffix', '密码'], ['method-focus', '显示名称'],
  ]
  const getCode = () => code.evaluate(el => (el as any).CodeMirror.getValue() as string)
  const edit = (value: string) => code.evaluate((el, value) => (el as any).CodeMirror.setValue(value), value)
  for (const [id, label] of apiChecks) {
    const entry = document.locator(`[data-api="${id}"]`)
    await entry.getByRole('button', { name: '交互示例', exact: true }).click()
    await expect(frame.getByLabel(label, { exact: true })).toBeVisible()
    await page.waitForFunction(() => !window.document.getAnimations().some(a => a.playState === 'running' && Number.isFinite(Number(a.effect?.getComputedTiming().endTime))))
    await expect(code).toHaveCount(1)
    await expect(page.locator('.vue-repl iframe')).toHaveCount(1)
    await expect(document.locator('.example-introduction')).toHaveCount(1)
    await expect(frame.locator('.apple-card')).toBeVisible()
    await expect(document).not.toContainText('Syntax error in import-map.json')
    if (id === 'prop-disabled' || id === 'prop-loading') {
      const toggle = frame.getByRole('switch', { name: id === 'prop-disabled' ? '禁用输入框' : '加载中' })
      const actions = frame.locator('.apple-input-wrap button')
      await expect(frame.getByLabel(label, { exact: true })).toBeDisabled()
      await expect(actions).toHaveCount(0)
      await expect(frame.locator('.apple-control__spinner')).toHaveCount(id === 'prop-loading' ? 1 : 0)
      await toggle.click()
      await expect(frame.getByLabel(label, { exact: true })).toBeEnabled()
      await expect(actions).toHaveCount(id === 'prop-disabled' ? 2 : 1)
      await toggle.click()
      await expect(actions).toHaveCount(0)
    }
    if (id === 'prop-type') {
      const source = await getCode()
      expect(source).toContain('<AppleSegmentedControl')
      await expect(frame.getByRole('radiogroup', { name: '输入类型' })).toBeVisible()
      await expect(frame.locator('html')).toHaveAttribute('data-apple-motion', 'full')
      await frame.getByText('密码', { exact: true }).click()
      const animationDurations = await frame.locator('.apple-segmented').evaluate(el => el.getAnimations({ subtree: true }).map(a => Number(a.effect?.getTiming().duration)))
      expect(animationDurations.some(duration => duration > 0)).toBe(true)
      await expect(frame.getByLabel('内容', { exact: true })).toHaveAttribute('type', 'password')
      await frame.getByRole('button', { name: '显示密码', exact: true }).click()
      await expect(frame.getByLabel('内容', { exact: true })).toHaveAttribute('type', 'text')
      await frame.getByText('数字', { exact: true }).click()
      await expect(frame.getByLabel('内容', { exact: true })).toHaveAttribute('type', 'number')
      await frame.getByText('文本', { exact: true }).click()
      await page.evaluate(() => (window.document.querySelector('#app') as any).__vue_app__.config.globalProperties.$apple.motion.value.set('none'))
      await expect(frame.locator('html')).toHaveAttribute('data-apple-motion', 'none')
      await frame.getByText('密码', { exact: true }).click()
      expect(await frame.locator('.apple-segmented').evaluate(el => el.getAnimations({ subtree: true }).filter(a => a.playState === 'running').length)).toBe(0)
      await page.evaluate(() => (window.document.querySelector('#app') as any).__vue_app__.config.globalProperties.$apple.motion.value.set('full'))
      await expect(frame.locator('html')).toHaveAttribute('data-apple-motion', 'full')
      await expect(frame.getByLabel('内容', { exact: true })).toHaveAttribute('type', 'text')
      expect(source).not.toContain('<select')
      await edit(source.replace("ref('123')", "ref('456')"))
      await expect(frame.getByLabel('内容', { exact: true })).toHaveValue('456')
      await edit('<template><div></template>')
      await expect(document).toContainText('Element is missing end tag')
      await edit(source)
      await expect(frame.getByLabel('内容', { exact: true })).toHaveValue('123')
      await edit(source.replace("const value = ref('123')", "throw new Error('示例运行错误'); const value = ref('123')"))
      await expect(document).toContainText('示例运行错误')
      await edit(source)
      await expect(frame.getByLabel('内容', { exact: true })).toBeVisible()
      const previewBounds = await page.locator('.vue-repl iframe').boundingBox(), editorBounds = await code.boundingBox()
      expect(previewBounds!.x + previewBounds!.width).toBeLessThanOrEqual(editorBounds!.x + 3)
      await expect(document).not.toContainText('示例运行错误')
      await page.waitForFunction(() => !window.document.getAnimations().some(a => a.playState === 'running' && Number.isFinite(Number(a.effect?.getComputedTiming().endTime))))
      await code.scrollIntoViewIfNeeded()
      await page.screenshot({ path: artifacts + '/api-page-desktop.png' })
    }
    if (id === 'prop-clearable') {
      await frame.getByRole('button', { name: '清空', exact: true }).click()
      await expect(frame.getByLabel('内容', { exact: true })).toHaveValue('')
      await expect(frame.getByRole('switch', { name: '允许清空' })).toBeVisible()
    }
    if (id === 'prop-required') {
      await frame.getByRole('button', { name: '提交', exact: true }).click()
      await expect(frame.locator('output')).toHaveText('等待提交')
      await frame.getByLabel(label, { exact: true }).fill('完成')
      await expect(frame.getByLabel(label, { exact: true })).toHaveValue('完成')
      await frame.getByRole('button', { name: '提交', exact: true }).click()
      await expect(frame.locator('output')).toHaveText('提交成功')
    }
    if (id === 'method-focus') {
      await frame.getByRole('button', { name: '调用 focus()' }).click()
      await expect(frame.getByLabel(label, { exact: true })).toBeFocused()
    }
  }
  const opened = await stats()
  const first = document.locator('[data-api="prop-type"]')
  await first.getByRole('button', { name: '交互示例', exact: true }).click()
  await expect(frame.getByLabel('内容', { exact: true })).toBeVisible()
  const original = await getCode()
  await edit(original.replace("ref('123')", "ref('草稿')"))
  await expect(frame.getByLabel('内容', { exact: true })).toHaveValue('草稿')
  await first.getByRole('button', { name: '交互示例', exact: true }).click()
  await expect(code).toHaveCount(0)
  await first.getByRole('button', { name: '交互示例', exact: true }).click()
  await expect(frame.getByLabel('内容', { exact: true })).toHaveValue('草稿')
  await first.getByRole('button', { name: '恢复示例' }).click()
  await expect(frame.getByLabel('内容', { exact: true })).toHaveValue('123')
  for (let i = 0; i < 3; i++) { await first.getByRole('button', { name: '重新运行' }).click(); await expect(frame.getByLabel('内容', { exact: true })).toBeVisible() }
  await page.evaluate(() => (window.document.querySelector('#app') as any).__vue_app__.config.globalProperties.$apple.theme.value.set('dark'))
  await expect(frame.locator('html')).toHaveCSS('color-scheme', 'dark')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.waitForFunction(() => !window.document.getAnimations().some(a => a.playState === 'running' && Number.isFinite(Number(a.effect?.getComputedTiming().endTime))))
  await page.locator('.vue-repl').scrollIntoViewIfNeeded()
  const previewBounds = await page.locator('.vue-repl iframe').boundingBox(), editorBounds = await code.boundingBox()
  expect(previewBounds!.y + previewBounds!.height).toBeLessThanOrEqual(editorBounds!.y + 3)
  expect(await page.evaluate(() => window.document.documentElement.scrollWidth)).toBe(390)
  await page.screenshot({ path: artifacts + '/api-page-mobile.png' })
  await first.getByRole('button', { name: '交互示例', exact: true }).click()
  await expect(code).toHaveCount(0)
  const closed = await stats()
  await page.getByRole('navigation', { name: '组件文档路径' }).getByRole('link', { name: '表单', exact: true }).click()
  await expect(page).toHaveURL(/\/components#apple-input$/)
  await expect(page.locator('.vue-repl iframe, .CodeMirror')).toHaveCount(0)
  await page.goto('/component-docs/apple-input')
  await expect(page.getByTestId('component-document').locator('.api-entry')).toHaveCount(17)
  await expect(page.locator('.CodeMirror')).toHaveCount(0)
  await writeFile(artifacts + '/metrics-v3.json', JSON.stringify({ before, opened, closed, apiCount: 17, exampleCount: apiChecks.length, resources: [...new Set(resources)], pageErrors: errors }, null, 2))
  expect(errors).toEqual([])
})
