import { test, expect } from '@playwright/test'

test('input API groups preserve anchors without duplicating the main demo', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/components#apple-input')
  const entry = page.locator('#apple-input .documentation-entry .apple-link')
  await expect(entry).toHaveText('代码与 API')
  await entry.click()
  await expect(page).toHaveURL(/\/component-docs\/apple-input$/)
  const document = page.getByTestId('component-document')
  await expect(document.locator('.api-entry')).toHaveCount(17)
  await expect(document.locator('.api-group')).toHaveCount(4)
  await expect(document.locator('.apple-card')).toHaveCount(0)
  await expect(document.getByRole('button', { name: '交互示例' })).toHaveCount(0)
  await expect(document.locator('.CodeMirror, iframe')).toHaveCount(0)
  const frame = page.frameLocator('[data-testid="input-playground"] .vue-repl iframe')
  await expect(frame.getByLabel('姓名', { exact: true })).toHaveValue('Apptify')
  await expect(page.locator('.vue-repl iframe')).toHaveCount(1)
  const tree = page.getByRole('tree', { name: '组件 API 树' })
  await tree.getByRole('treeitem', { name: 'clearable', exact: true }).click()
  await expect(page).toHaveURL(/#prop-clearable$/)
  await expect(document.locator('#prop-clearable')).toBeInViewport()
  await expect(document.locator('#prop-clearable .api-type')).toHaveText('boolean')
  await expect(document.locator('#prop-clearable .api-default')).toContainText('false')
  await page.screenshot({ path: 'test-results/input-api-desktop.png' })
  await tree.getByRole('treeitem', { name: 'focus()', exact: true }).click()
  await expect(page).toHaveURL(/#method-focus$/)
  await expect(document.locator('#method-focus')).toBeInViewport()
  await page.setViewportSize({ width: 390, height: 844 })
  await document.locator('#props').scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/input-api-mobile.png' })
  await page.getByRole('navigation', { name: '组件文档路径' }).getByRole('link', { name: '表单', exact: true }).click()
  await expect(page).toHaveURL(/\/components#apple-input$/)
  await expect(page.locator('.vue-repl iframe')).toHaveCount(0)
  expect(errors).toEqual([])
})
