import { test, expect } from '@playwright/test'

test('Vue editor compiles configuration and manual edits, copies edited source and uses plain preview sections', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/component-docs/apple-input')
  const playground = page.getByTestId('input-playground')
  const frame = page.frameLocator('[data-testid="input-playground"] .vue-repl iframe')
  const config = playground.getByRole('region', { name: '输入框配置' })
  const editor = playground.locator('.CodeMirror')
  const getCode = () => editor.evaluate(el => (el as any).CodeMirror.getValue() as string)
  await expect(frame.getByLabel('姓名', { exact: true })).toHaveValue('Apptify')
  await expect(frame.locator('.apple-card')).toHaveCount(0)
  await expect(playground).not.toContainText('LIVE PREVIEW')
  const switchLayout = await config.locator('.apple-switch-row').first().evaluate(row => ({
    text: row.querySelector('.apple-choice__label')!.getBoundingClientRect().right,
    control: row.querySelector('.apple-switch')!.getBoundingClientRect().left,
  }))
  expect(switchLayout.text).toBeLessThanOrEqual(switchLayout.control)
  await config.getByRole('radiogroup', { name: '快速场景' }).getByText('密码', { exact: true }).click()
  await expect(frame.getByLabel('密码', { exact: true })).toHaveAttribute('type', 'password')
  await frame.getByRole('button', { name: '显示密码', exact: true }).click()
  await expect(frame.getByLabel('密码', { exact: true })).toHaveAttribute('type', 'text')
  await config.getByRole('switch', { name: '加载', exact: true }).click()
  await expect(frame.getByLabel('密码', { exact: true })).toBeDisabled()
  await expect(frame.locator('.apple-control__spinner')).toHaveCount(1)
  expect(await getCode()).toContain('          loading')
  await config.getByRole('switch', { name: '加载', exact: true }).click()
  await expect(frame.getByLabel('密码', { exact: true })).toBeEnabled()
  await frame.getByRole('button', { name: '清空', exact: true }).click()
  await expect(frame.getByLabel('密码', { exact: true })).toHaveValue('')
  await expect(frame.getByRole('textbox', { name: '事件记录内容' })).toHaveValue(/update:modelValue/)
  await expect(frame.getByRole('textbox', { name: '事件记录内容' })).toHaveValue(/clear/)
  await config.getByRole('button', { name: '重置', exact: true }).click()
  await expect(frame.getByLabel('姓名', { exact: true })).toBeVisible()
  await config.getByLabel('标签', { exact: true }).fill('新名称')
  await expect(frame.getByLabel('新名称', { exact: true })).toBeVisible()
  await playground.getByRole('tab', { name: 'App.vue', exact: true }).click()
  await expect(config).not.toBeVisible()
  await expect(editor).toBeVisible()
  const source = await getCode()
  expect(source).toContain('export default {')
  expect(source).toContain('label="新名称"')
  expect(source).not.toContain('v-bind=')
  await editor.evaluate((el, code) => (el as any).CodeMirror.setValue(code), source.replace('新名称', '源码修改'))
  await expect(frame.getByLabel('源码修改', { exact: true })).toBeVisible()
  await playground.getByRole('button', { name: '复制当前文件', exact: true }).click()
  await expect(playground.getByRole('status')).toContainText('已复制当前文件')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(await getCode())
  await playground.getByRole('button', { name: '恢复当前配置', exact: true }).click()
  await expect(frame.getByLabel('姓名', { exact: true })).toBeVisible()
  await playground.locator('.live-editor').scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/input-playground-code.png' })
  await playground.getByRole('tab', { name: '低代码', exact: true }).click()
  await expect(config).toBeVisible()
  await expect(config.getByLabel('标签', { exact: true })).toHaveValue('姓名')
  await expect(editor).not.toBeVisible()
  await expect(playground.locator('.mode-selector').getByRole('button')).toHaveCount(3)
  await config.getByRole('radiogroup', { name: '快速场景' }).getByText('邮箱', { exact: true }).click()
  await expect(frame.locator('.apple-input__affix svg')).toBeVisible()
  await expect(frame.getByRole('textbox', { name: '电子邮箱', exact: true })).toHaveAttribute('type', 'email')
  await expect(frame.locator('body')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await frame.getByRole('textbox', { name: '电子邮箱', exact: true }).fill('a@example.com')
  await expect(frame.locator('.event-log')).toHaveCSS('max-height', '180px')
  await expect(frame.locator('.event-log')).toHaveAttribute('readonly', '')
  await expect(frame.locator('.event-log')).toHaveCSS('resize', 'none')
  await expect(frame.locator('.event-log')).toHaveCSS('border-top-style', 'solid')
  await expect(frame.locator('.event-log')).toHaveCSS('border-top-width', '1px')
  await frame.getByRole('textbox', { name: '电子邮箱', exact: true }).pressSequentially('abcdefghijklmnop')
  await expect.poll(async () => (await frame.locator('.event-log').inputValue()).split('\n').length).toBe(12)
  const log = await frame.locator('.event-log').evaluate(el => ({ height: el.getBoundingClientRect().height, scroll: el.scrollHeight, client: el.clientHeight }))
  expect(log.height).toBe(180)
  expect(log.scroll).toBeGreaterThan(log.client)
  const bottomGap = () => frame.locator('.event-log').evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop)
  await expect.poll(bottomGap).toBeLessThanOrEqual(1)
  await frame.locator('.event-log').evaluate(el => el.scrollTop = 0)
  await frame.getByRole('textbox', { name: '电子邮箱', exact: true }).pressSequentially('q')
  await expect.poll(bottomGap).toBeLessThanOrEqual(1)
  await frame.locator('.event-heading').getByRole('button', { name: '清除记录' }).click()
  await expect(frame.locator('.event-log')).toHaveValue('')
  await expect.poll(() => frame.locator('.event-log').evaluate(el => el.scrollTop)).toBe(0)
  await expect(frame.locator('.event-log')).toHaveAttribute('placeholder', '等待操作…')
  await playground.locator('.live-editor').scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/input-playground-desktop.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(config.locator('.preset-segments')).not.toBeVisible()
  await expect(config.locator('.preset-select')).toBeVisible()
  await playground.locator('.live-editor').scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/input-playground-mobile.png' })
})

test('prefix and suffix accept text or icon codes and validate unknown icons', async ({ page }) => {
  await page.goto('/component-docs/apple-input')
  const playground = page.getByTestId('input-playground')
  const config = playground.getByRole('region', { name: '输入框配置' })
  const frame = page.frameLocator('[data-testid="input-playground"] .vue-repl iframe')
  await expect(frame.getByLabel('姓名', { exact: true })).toHaveValue('Apptify')
  await config.getByRole('button', { name: '插槽、原生属性与动效', exact: true }).click()
  const prefix = config.getByRole('radiogroup', { name: '前缀插槽', exact: true })
  const suffix = config.getByRole('radiogroup', { name: '后缀插槽', exact: true })
  await prefix.getByText('图标', { exact: true }).click()
  await config.getByLabel('前缀图标代号', { exact: true }).fill('User')
  await suffix.getByText('图标', { exact: true }).click()
  await config.getByLabel('后缀图标代号', { exact: true }).fill('arrow-right')
  await expect(frame.locator('.apple-input__affix svg')).toHaveCount(2)
  const code = () => playground.locator('.CodeMirror').evaluate(el => (el as any).CodeMirror.getValue() as string)
  await expect.poll(code).toContain("import { User, ArrowRight } from 'lucide-vue-next'")
  await config.getByLabel('后缀图标代号', { exact: true }).fill('NoSuchIcon')
  await expect(config).toContainText('请输入有效图标代号')
  await expect(frame.locator('.apple-input__affix svg')).toHaveCount(1)
  await suffix.getByText('文字', { exact: true }).click()
  await config.getByLabel('后缀文字', { exact: true }).fill('kg')
  await expect(frame.locator('.apple-input__affix').last()).toHaveText('kg')
  await prefix.getByText('无', { exact: true }).click()
  await suffix.getByText('无', { exact: true }).click()
  await expect(frame.locator('.apple-input__affix')).toHaveCount(0)
  await expect.poll(code).not.toContain("from 'lucide-vue-next'")
})
