import { expect, test } from '@playwright/test'

test('global ripple switch persists and automatically follows motion policy', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/settings')
  const toggle = page.getByRole('switch', { name: '点击波纹', exact: true })
  const motion = page.getByRole('radiogroup', { name: '全局动效', exact: true })
  await motion.getByText('完整', { exact: true }).click()
  await expect(toggle).toBeChecked()
  await toggle.uncheck()
  await page.reload()
  await expect(toggle).not.toBeChecked()
  await toggle.check()
  await motion.getByText('减弱', { exact: true }).click()
  await expect(toggle).toBeEnabled()
  await expect(toggle).not.toBeChecked()
  await toggle.check()
  await page.reload()
  await expect(toggle).toBeEnabled()
  await expect(toggle).toBeChecked()
  await motion.getByText('关闭', { exact: true }).click()
  await expect(toggle).toBeDisabled()
  await expect(toggle).not.toBeChecked()
  await motion.getByText('完整', { exact: true }).click()
  await expect(toggle).toBeEnabled()
  await toggle.check()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(toggle).toBeEnabled()
  await expect(toggle).not.toBeChecked()
  await toggle.check()
  await page.reload()
  await expect(toggle).toBeChecked()
})
