import { expect, test } from '@playwright/test'

const vertical = '.apple-scroll-bar--vertical[aria-controls="port"]'
const horizontal = '.apple-scroll-bar--horizontal[aria-controls="port"]'
test.beforeEach(async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 900 })
  await page.goto('/tests/e2e/fixtures/scrollbar.html')
  await expect(page.locator(vertical)).toBeVisible()
})

test('fixed tracks remove native gutters and follow transformed targets, resize and scroll', async ({ page }) => {
  await expect(page.locator(vertical)).toHaveCSS('position', 'fixed')
  expect(await page.locator('#port').evaluate(element => element.clientWidth)).toBe(316)
  const aligned = () => page.locator(vertical).evaluate(bar => {
    const port = document.querySelector('#port')!.getBoundingClientRect(), track = bar.getBoundingClientRect()
    return Math.abs(track.right - (port.right - 2))
  })
  expect(await aligned()).toBeLessThan(1)
  await page.evaluate(() => window.scrollTo(0, 80))
  await expect.poll(aligned).toBeLessThan(1)
  await page.locator('#port').evaluate(element => { element.scrollTop = 180 })
  await expect(page.locator(vertical)).toHaveAttribute('aria-valuenow', '180')
  await page.locator('#port').evaluate(element => { (element as HTMLElement).style.height = '300px' })
  await expect(page.locator(vertical)).toHaveAttribute('aria-valuemax', '504')
  await page.screenshot({ path: 'test-results/scrollbar-light.png' })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.screenshot({ path: 'test-results/scrollbar-dark.png' })
})

test('vertical dragging, keyboard, wheel and RTL horizontal dragging synchronize native scroll', async ({ page }) => {
  const bar = page.locator(vertical), thumb = bar.locator('span')
  const track = (await bar.boundingBox())!, box = (await thumb.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2 + (track.height - box.height) / 2, { steps: 6 })
  await page.mouse.up()
  await expect.poll(() => page.locator('#port').evaluate(element => element.scrollTop)).toBeCloseTo(302, 0)
  await bar.press('End')
  await expect(bar).toHaveAttribute('aria-valuenow', '604')
  await bar.press('Home')
  await expect(bar).toHaveAttribute('aria-valuenow', '0')
  await bar.hover()
  await page.mouse.wheel(0, 80)
  await expect(bar).toHaveAttribute('aria-valuenow', '80')
  await page.locator('#rtl').click()
  const xbar = page.locator(horizontal)
  await xbar.press('End')
  await expect.poll(() => page.locator('#port').evaluate(element => element.scrollLeft)).toBe(-404)
  await xbar.press('Home')
  await expect(xbar).toHaveAttribute('aria-valuenow', '0')
  await xbar.press('ArrowLeft')
  await expect(xbar).toHaveAttribute('aria-valuenow', '40')
})

test('dynamic overflow, clipping, opt out, modal stacking and cleanup', async ({ page }) => {
  const dynamic = page.locator('.apple-scroll-bar--vertical[aria-controls="dynamic"]')
  await expect(dynamic).toBeHidden()
  await page.locator('#grow').click()
  await expect(dynamic).toBeVisible()
  await page.locator('#grow').click()
  await expect(dynamic).toBeHidden()
  expect(await page.locator('#ignored').getAttribute('data-apple-scrollbar-native')).toBeNull()
  await expect(page.locator('.apple-scroll-bar[aria-controls="explicit"]')).toHaveCount(1)
  const clipped = await page.locator('.apple-scroll-bar--vertical[aria-controls="nested"]').boundingBox()
  const parent = await page.locator('.nest').boundingBox()
  expect(clipped!.y + clipped!.height).toBeLessThanOrEqual(parent!.y + parent!.height)
  await page.locator('#open').click()
  await expect(page.locator(vertical)).toBeHidden()
  const modal = page.getByRole('dialog'), modalBar = modal.locator('.apple-scroll-bar--vertical')
  await expect(modalBar).toBeVisible()
  await modalBar.press('End')
  expect(await modal.locator('.apple-modal-body').evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  await page.evaluate(() => (window as unknown as { unmount(): void }).unmount())
  await expect(page.locator('.apple-scroll-bar')).toHaveCount(0)
  await expect(page.locator('[data-apple-scrollbar-native]')).toHaveCount(0)
})

test('scrollbars inherit layer bounds and remain in their owning overlay stack', async ({ page }) => {
  const bar = page.locator(vertical)
  const nav = page.locator('.apple-navibar__bar')
  expect(Number(await bar.evaluate(element => getComputedStyle(element).zIndex))).toBeGreaterThan(Number(await nav.evaluate(element => getComputedStyle(element).zIndex)))
  await expect(bar).not.toHaveAttribute('popover')
  await page.locator('#transformed').evaluate(element => { Object.assign((element as HTMLElement).style, { position: 'relative', zIndex: '300' }) })
  await expect(bar).toHaveCSS('z-index', '300')
  await page.locator('#transformed').evaluate(element => { (element as HTMLElement).style.zIndex = '10' })
  await expect(bar).toHaveCSS('z-index', '80')
  await page.getByRole('button', { name: '打开浮层', exact: true }).click()
  const popup = page.locator('.apple-popover'), popupBar = popup.locator('.apple-scroll-bar--vertical')
  await expect(popupBar).toBeVisible()
  await expect(popupBar).toHaveCSS('z-index', '1200')
  expect(await popupBar.evaluate(element => {
    const track = element.getBoundingClientRect(), owner = element.parentElement!.getBoundingClientRect()
    return Math.abs(track.right - (owner.right - 1))
  })).toBeLessThan(2)
  await popupBar.press('End')
  expect(await popup.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  await page.keyboard.press('Escape')
  await page.locator('#open').click()
  const lower = page.getByRole('dialog', { name: '长内容' }), lowerBar = lower.locator('.apple-scroll-bar--vertical')
  await expect(lowerBar).toBeVisible()
  await expect(lowerBar).toHaveCSS('z-index', '1200')
  await lower.getByRole('button', { name: '对话框内浮层', exact: true }).click()
  const innerPopup = page.locator('.apple-popover[aria-label="对话框内浮层"]')
  const innerBar = innerPopup.locator('.apple-scroll-bar--vertical')
  await expect(innerBar).toBeVisible()
  await expect(innerBar).toHaveCSS('z-index', '1220')
  await innerBar.press('End')
  expect(await innerPopup.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  await page.keyboard.press('Escape')
  await page.locator('#upper').click()
  const upper = page.getByRole('dialog', { name: '第二层' }), upperBar = upper.locator('.apple-scroll-bar--vertical')
  await expect(upperBar).toBeVisible()
  await expect(upperBar).toHaveCSS('z-index', '1220')
  await expect(lowerBar).toBeHidden()
  await upperBar.press('End')
  expect(await upper.locator('.apple-modal-body').evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  await upper.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(lowerBar).toBeVisible()
})

test('narrow edge hit areas keep the cursor and hover only the slider', async ({ page }) => {
  const rootBar = page.getByRole('scrollbar', { name: '页面滚动条' }).filter({ has: page.locator('span') }).locator('visible=true')
  const thumb = (await rootBar.locator('span').boundingBox())!
  const y = thumb.y + thumb.height / 2
  await page.mouse.move(899, y)
  await expect(rootBar).toHaveCSS('width', '12px')
  await expect(rootBar.locator('.apple-scroll-bar__slider')).toHaveCSS('width', '8px')
  await expect(rootBar.locator('span')).toHaveCSS('margin', '0px 1px')
  await expect(rootBar).toHaveCSS('cursor', 'auto')
  await expect(rootBar.locator('span')).toHaveCSS('cursor', 'auto')
  await expect(rootBar.locator('span')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0.5)')
  await page.mouse.move(899, thumb.y + thumb.height + 10)
  await expect(rootBar.locator('span')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0.32)')
  await page.mouse.move(899, y)
  await expect(rootBar).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  expect(await rootBar.evaluate((bar, y) => document.elementFromPoint(899, y)?.closest('.apple-scroll-bar') === bar, y)).toBe(true)
  expect(await rootBar.evaluate(bar => getComputedStyle(bar, '::before').content)).toBe('none')
  await page.mouse.down()
  await expect(rootBar).toHaveClass(/is-dragging/)
  await expect(rootBar).toHaveCSS('cursor', 'auto')
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
  await page.mouse.move(899, y + 80, { steps: 8 })
  await page.mouse.up()
  expect(await page.evaluate(() => window.scrollY)).toBeGreaterThan(0)
  await page.locator(horizontal).scrollIntoViewIfNeeded()
  await expect(page.locator(horizontal)).toHaveCSS('height', '12px')
})
