import { expect, test } from '@playwright/test'

test('appearance has four navigable settings with responsive columns and live demonstrations', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/settings')
  const tree = page.getByRole('tree', { name: '设置目录' })
  const appearance = tree.getByRole('treeitem', { name: '外观设置', exact: true })
  await expect(appearance).toHaveAttribute('aria-level', '2')
  await expect(appearance).toHaveAttribute('aria-expanded', 'true')
  for (const label of ['主题', '动效', '点击波纹', '玻璃效果']) {
    await expect(tree.getByRole('treeitem', { name: label, exact: true })).toHaveAttribute('aria-level', '3')
  }
  await tree.getByRole('treeitem', { name: '玻璃效果', exact: true }).click()
  await expect(page.locator('#setting-glass')).toBeFocused()
  await expect(tree.getByRole('treeitem', { name: '玻璃效果', exact: true })).toHaveAttribute('aria-selected', 'true')
  await tree.getByRole('treeitem', { name: '设置', exact: true }).locator('.apple-tree__row').first().click()
  await expect(appearance).toHaveCount(0)
  await tree.getByRole('treeitem', { name: '设置', exact: true }).locator('.apple-tree__row').first().click()
  await expect(appearance).toBeVisible()
  const panel = await page.locator('.settings-content').boundingBox()
  const sidebar = await page.locator('.settings-sidebar').boundingBox()
  expect(panel!.width).toBeGreaterThan(840)
  expect(await page.locator('.settings-grid').evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length)).toBe(3)
  expect(sidebar!.x + sidebar!.width).toBeLessThan(panel!.x)
  await expect(page.locator('.settings-grid > .apple-card')).toHaveCount(4)
  const motion = page.getByRole('radiogroup', { name: '全局动效', exact: true })
  await motion.getByText('完整', { exact: true }).click()
  const accordion = page.locator('.motion-sample').getByRole('button', { name: '展开看看', exact: true })
  const rippleButton = page.locator('.ripple-sample').getByRole('button', { name: '试试点击波纹', exact: true })
  // Observe the library's actual ripple nodes, rather than a decorative animation.
  await rippleButton.evaluate(el => {
    el.setAttribute('data-observed-waves', '0')
    new MutationObserver(records => {
      for (const record of records) for (const node of record.addedNodes) {
        if (node instanceof Element && node.classList.contains('v-ripple__container')) {
          el.setAttribute('data-observed-waves', String(Number(el.getAttribute('data-observed-waves')) + 1))
        }
      }
    }).observe(el, { childList: true })
  })
  await expect(accordion).toHaveAttribute('aria-expanded', 'true', { timeout: 6000 })
  await expect(accordion).toHaveAttribute('aria-expanded', 'false', { timeout: 6000 })
  await expect.poll(() => rippleButton.getAttribute('data-observed-waves')).not.toBe('0')
  await expect(page.locator('.ripple-click-count')).not.toHaveText('已点击 0 次')
  await expect(page.locator('.glass-sample-colors')).toHaveCSS('animation-name', /sample-glass/)
  await page.getByRole('switch', { name: '点击波纹', exact: true }).uncheck()
  const clicks = await page.locator('.ripple-click-count').textContent()
  await page.waitForTimeout(2800)
  await expect(page.locator('.ripple-click-count')).toHaveText(clicks!)
  await expect(rippleButton.locator('.v-ripple__container')).toHaveCount(0)
  await motion.getByText('减弱', { exact: true }).click()
  await expect(page.locator('.motion-sample .apple-accordion__region')).toHaveCSS('transition-duration', '0.08s')
  await motion.getByText('关闭', { exact: true }).click()
  const expanded = await accordion.getAttribute('aria-expanded')
  await page.waitForTimeout(2800)
  await expect(accordion).toHaveAttribute('aria-expanded', expanded!)
  await expect(page.locator('.motion-sample .apple-accordion__region')).toHaveCSS('transition-duration', '0s')
  await accordion.click()
  await expect(accordion).toHaveAttribute('aria-expanded', expanded === 'true' ? 'false' : 'true')
  await expect(page.locator('.glass-sample-colors')).toHaveCSS('animation-name', 'none')
})


test('glass resets independently to fifty percent opacity and twelve pixel blur', async ({ page }) => {
  await page.goto('/settings')
  await page.getByRole('button', { name: '深色', exact: true }).click()
  await page.getByRole('radiogroup', { name: '全局动效', exact: true }).getByText('关闭', { exact: true }).click()
  const opacity = page.getByRole('slider', { name: '玻璃不透明度', exact: true })
  const blur = page.getByRole('slider', { name: '玻璃模糊', exact: true })
  await expect(opacity).toHaveValue('50')
  await opacity.focus()
  await opacity.press('End')
  await blur.focus()
  await blur.press('End')
  await page.getByRole('button', { name: '恢复默认玻璃效果', exact: true }).click()
  await expect(opacity).toHaveValue('50')
  await expect(blur).toHaveValue('12')
  await expect(page.getByRole('button', { name: '深色', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('main')).toHaveAttribute('data-preview-motion', 'none')
  await page.reload()
  await expect(opacity).toHaveValue('50')
  await expect(blur).toHaveValue('12')
})
