import { expect, test } from '@playwright/test'
import { catalog } from '../../playground/catalog'

test('home, components and settings are separate routes with browser history', async ({ page }) => {
  await page.goto('/')
  const nav = page.getByRole('navigation', { name: '主导航', exact: true })
  await expect(nav.getByRole('link')).toHaveText(['首页', '组件', '设置'])
  await expect(page.locator('.sidebar')).toHaveCount(0)
  await expect(page.locator('.specimen')).toHaveCount(6)
  await nav.getByRole('link', { name: '组件', exact: true }).click()
  await expect(page).toHaveURL(/\/components$/)
  await expect(page.locator('.sidebar')).toBeVisible()
  await expect(page.locator('.component-demo')).toHaveCount(catalog.length)
  await nav.getByRole('link', { name: '设置', exact: true }).click()
  await expect(page).toHaveURL(/\/settings$/)
  await expect(page.locator('.sidebar')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: '设置。', exact: true })).toBeVisible()
  await expect(nav.getByRole('link', { name: '设置', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.goBack()
  await expect(page.locator('.component-demo')).toHaveCount(catalog.length)
  await page.goBack()
  await expect(page.locator('.home-intro')).toBeVisible()
})

test('the component index locates previews without filtering the feed', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/components')
  await page.locator('.sidebar a[href="/components#forms"]').click()
  await expect(page).toHaveURL(/#forms$/)
  await expect(page.locator('#forms')).toBeInViewport()
  await expect(page.locator('.component-demo')).toHaveCount(catalog.length)
  await page.locator('.sidebar a[href="/components#apple-input"]').click()
  await expect(page.locator('#apple-input')).toBeInViewport()
  await page.locator('#apple-input input').fill('保持预览状态')
  await page.locator('.sidebar a[href="/components#feedback"]').click()
  await expect(page.locator('#feedback')).toBeInViewport()
  await page.locator('#apple-input .component-card-heading a').click()
  await expect(page.locator('#apple-input input')).toHaveValue('保持预览状态')
  await expect(page.locator('.sidebar a[href="/components#apple-input"]')).toHaveAttribute('aria-current', 'location')
  const source = page.locator('#apple-input .component-source').getByRole('button', { name: '代码与 API', exact: true })
  await expect(source).toHaveAttribute('aria-expanded', 'false')
  await source.click()
  await expect(source).toHaveAttribute('aria-expanded', 'true')
  const region = page.locator(`[id="${await source.getAttribute('aria-controls')}"]`)
  await expect(region).toHaveAttribute('role', 'region')
  await expect(region).toHaveAttribute('aria-hidden', 'false')
  await expect(page.locator('#apple-input .code-view')).toBeVisible()
  await expect(page.locator('#apple-input .component-demo')).toBeVisible()
  await expect(page.getByText('工作空间', { exact: true })).toHaveCount(0)
})

test('a direct component anchor survives refresh and scrolling updates the index', async ({ page }) => {
  await page.goto('/components#apple-table')
  await expect(page.locator('#apple-table')).toBeInViewport()
  await expect(page.locator('.sidebar a[href="/components#apple-table"]')).toHaveAttribute('aria-current', 'location')
  await page.reload()
  await expect(page.locator('#apple-table')).toBeInViewport()
  await page.locator('#apple-dialog').evaluate(element => window.scrollTo({ top: element.getBoundingClientRect().top + window.scrollY - 100, behavior: 'instant' }))
  await expect(page.locator('.sidebar a[href="/components#apple-dialog"]')).toHaveAttribute('aria-current', 'location')
})

test('account popup supports dismissal, example forms and settings navigation', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByRole('button', { name: '打开用户菜单', exact: true })
  const popup = page.getByRole('dialog', { name: '用户菜单', exact: true })
  await trigger.click()
  await expect(popup.getByText('lin.chu@example.com')).toBeVisible()
  await expect(popup.locator('.apple-avatar')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(popup).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()
  await page.locator('h1').click()
  await expect(popup).toHaveCount(0)
  for (const [mode, label] of [['Login', '登录'], ['Register', '注册']]) {
    await trigger.click()
    await popup.getByRole('button', { name: new RegExp(mode) }).click()
    const form = page.getByRole('dialog', { name: `${label}示例`, exact: true })
    await expect(form).toBeVisible()
    if (mode === 'Register') await form.getByLabel('姓名', { exact: true }).fill('林初')
    await form.getByLabel('电子邮箱', { exact: true }).fill('demo@example.com')
    await form.getByLabel('密码', { exact: true }).fill('example-password')
    await form.getByRole('button', { name: `体验${label}`, exact: true }).click()
    await expect(form).toHaveCount(0)
    await expect(page.getByText(`${label}示例已完成`, { exact: true })).toBeVisible()
  }
  await trigger.click()
  await popup.getByRole('link', { name: '偏好设置', exact: true }).click()
  await expect(page).toHaveURL(/\/settings$/)
  await expect(popup).toHaveCount(0)
})

test('theme and motion preferences persist across routes and reloads', async ({ page }) => {
  await page.goto('/settings')
  await page.getByRole('button', { name: '深色', exact: true }).click()
  await page.getByRole('radiogroup', { name: '全局动效', exact: true }).getByText('关闭', { exact: true }).click()
  await expect(page.locator('#app > .apple-provider')).toHaveAttribute('data-apple-theme', 'dark')
  await expect(page.locator('#app > .apple-provider')).toHaveAttribute('data-apple-motion', 'none')
  await page.getByRole('navigation', { name: '主导航', exact: true }).getByRole('link', { name: '首页', exact: true }).click()
  await expect(page.locator('#app > .apple-provider')).toHaveAttribute('data-apple-theme', 'dark')
  await page.reload()
  await expect(page.locator('#app > .apple-provider')).toHaveAttribute('data-apple-motion', 'none')
  await page.goto('/settings')
  await expect(page.getByRole('button', { name: '深色', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '恢复默认设置', exact: true }).click()
  await expect(page.locator('#app > .apple-provider')).toHaveAttribute('data-apple-theme', 'light')
})

for (const width of [320, 390, 768, 1440]) {
  test(`all three pages fit at ${width}px and the user control stays at the right`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    for (const route of ['/', '/components', '/settings']) {
      await page.goto(route)
      await expect(page.locator('main')).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
      const user = await page.getByRole('button', { name: '打开用户菜单', exact: true }).boundingBox()
      expect(user!.x + user!.width).toBeGreaterThan(width - 34)
      if (route === '/components' && width <= 800) {
        await page.getByRole('button', { name: '组件目录', exact: true }).click()
        const drawer = page.getByRole('dialog', { name: '组件目录', exact: true })
        await drawer.locator('a[href="/components#feedback"]').click()
        await expect(drawer).toHaveCount(0)
        await expect(page.locator('#feedback')).toBeInViewport()
        await expect(page.locator('.component-demo')).toHaveCount(catalog.length)
      }
    }
    expect(errors).toEqual([])
  })
}
