import { test, expect } from '@playwright/test'
import { waitForPageLayout } from './component-navigation'

for (const [path, query, result] of [['/components', 'AppleInput', '输入框'], ['/component-docs/apple-input', 'clearable', 'clearable']]) {
  test(`desktop search stays above the independently scrolling tree on ${path}`, async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 })
    await page.goto(path)
    await waitForPageLayout(page)
    const directory = page.locator('.directory-index')
    const search = directory.getByRole('searchbox')
    const scroll = directory.locator('.apple-tree-scroll')
    await expect(search).toBeVisible()
    const before = (await search.boundingBox())!
    await expect.poll(() => scroll.evaluate(element => element.scrollHeight - element.clientHeight)).toBeGreaterThan(100)
    await scroll.evaluate(element => { element.scrollTop = element.scrollHeight })
    await expect.poll(() => scroll.evaluate(element => element.scrollTop)).toBeGreaterThan(100)
    expect((await search.boundingBox())!.y).toBeCloseTo(before.y, 0)
    await expect(search).toBeInViewport()
    expect(await directory.evaluate(element => element.scrollTop)).toBe(0)
    await search.fill(query)
    await expect(directory.getByRole('treeitem', { name: result, exact: true })).toBeVisible()
    await expect(search).toBeFocused()
    expect((await search.boundingBox())!.y).toBeCloseTo(before.y, 0)
  })
}

test('mobile directory keeps search visible and height stable across filtering, expansion and TabBar changes', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/tests/e2e/fixtures/speed-dial.html')
  await page.getByRole('button', { name: '展开目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  const search = dialog.getByRole('searchbox', { name: '搜索接口目录' })
  await expect(search).toBeVisible()
  const before = await dialog.boundingBox()
  const inputBefore = await search.boundingBox()
  expect(before!.height).toBeGreaterThan(700)
  await search.fill('参数 80')
  await expect(dialog.getByRole('treeitem', { name: '参数 80', exact: true })).toBeVisible()
  await expect(dialog.getByRole('treeitem', { name: '参数 1', exact: true })).toHaveCount(0)
  await expect(search).toBeFocused()
  expect((await search.boundingBox())!.y).toBeCloseTo(inputBefore!.y, 0)
  expect((await dialog.boundingBox())!.height).toBeCloseTo(before!.height, 0)
  await search.fill('不存在')
  await expect(dialog.getByRole('status')).toHaveText('无匹配结果')
  expect((await search.boundingBox())!.y).toBeCloseTo(inputBefore!.y, 0)
  await search.fill('')
  await dialog.locator('.apple-tree-scroll').evaluate(element => { element.scrollTop = element.scrollHeight })
  await expect(search).toBeInViewport()
  await dialog.getByRole('tab', { name: '设置目录' }).click()
  await expect(dialog.getByRole('searchbox', { name: '搜索设置目录' })).toBeVisible()
  expect((await dialog.boundingBox())!.height).toBeCloseTo(before!.height, 0)
  await dialog.getByRole('tab', { name: '接口目录' }).click()
  await search.fill('参数 80')
  await page.screenshot({ path: 'artifacts/speed-dial-mobile.png' })
  await dialog.getByRole('treeitem', { name: '参数 80', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.locator('#selected')).toHaveText('prop-80')
  await page.getByRole('button', { name: '展开目录', exact: true }).click()
  await expect(search).toHaveValue('参数 80')
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await page.setViewportSize({ width: 1280, height: 844 })
  await expect(page.getByRole('button', { name: '展开目录', exact: true })).toHaveCount(0)
  await expect(page.locator('.apple-tree-host').getByRole('searchbox', { name: '搜索接口目录' })).toHaveValue('参数 80')
})

test('global actions follow BackTop, with primary directory button last', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/tests/e2e/fixtures/speed-dial.html')
  await page.getByRole('button', { name: '新增', exact: true }).click()
  await expect(page.locator('#count')).toHaveText('1')
  await page.evaluate(() => window.scrollTo({ top: 500, behavior: 'instant' }))
  const names = ['回到顶部', '新增', '第二操作', '展开目录']
  const bounds = []
  for (const name of names) {
    const button = page.getByRole('button', { name, exact: true })
    await expect(button).toBeVisible()
    bounds.push((await button.boundingBox())!)
  }
  expect(bounds.every((box, i) => !i || box.y > bounds[i - 1].y)).toBe(true)
  expect(bounds.every(box => box.x > 300)).toBe(true)
  await expect(page.getByRole('button', { name: '展开目录', exact: true })).toHaveClass(/apple-button--primary/)
  await page.getByRole('button', { name: '回到顶部', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
})

test('playground has one global host and unregisters the previous route directory', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/components')
  await expect(page.locator('.apple-speed-dial')).toHaveCount(1)
  await page.getByRole('button', { name: '展开目录', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('tree')).toHaveCount(1)
  await dialog.getByRole('searchbox').fill('AppleInput')
  await expect(dialog.getByRole('treeitem', { name: '输入框', exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: '打开主导航', exact: true }).click()
  await page.getByRole('link', { name: '设置', exact: true }).click()
  await expect(page).toHaveURL(/\/settings$/)
  await page.getByRole('button', { name: '展开目录', exact: true }).click()
  await expect(dialog.getByRole('tree')).toHaveAttribute('aria-label', '设置目录')
  await expect(dialog.getByRole('tab')).toHaveCount(0)
  expect(errors).toEqual([])
})
