import { expect, test } from '@playwright/test'

for (const width of [320, 390, 768, 1440]) {
  test(`steps independent hit areas and buttons fit at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/components#apple-steps')
    const steps = page.locator('#apple-steps .apple-steps')
    const circles = steps.locator('button.apple-steps__number')
    const labels = steps.locator('button.apple-steps__label')
    await expect(circles).toHaveCount(3)
    const current = () => steps.locator('li[aria-current="step"]')
    await expect(current()).toContainText('确认信息')
    const first = await steps.locator('li').first().boundingBox()
    await page.mouse.move(first!.x + 1, first!.y + 22)
    await page.mouse.click(first!.x + 1, first!.y + 22)
    await expect(current()).toContainText('确认信息')
    await expect(steps.locator('.v-ripple__container')).toHaveCount(0)
    const gap = await steps.locator('li').first().boundingBox()
    await page.mouse.click(gap!.x + gap!.width / 2, gap!.y + 48)
    await expect(current()).toContainText('确认信息')
    await labels.nth(2).hover()
    await expect(labels.nth(2)).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await labels.nth(2).click()
    await expect(current()).toContainText('完成')
    await expect(labels.nth(2).locator('.v-ripple__container')).toHaveCount(0)
    await circles.nth(0).hover()
    await expect.poll(() => circles.nth(0).evaluate(el => getComputedStyle(el).backgroundColor === getComputedStyle(el).borderColor)).toBe(true)
    for (const index of [0, 2, 1, 2, 0]) await circles.nth(index).click()
    await expect(current()).toContainText('选择产品')
    await labels.nth(1).focus()
    await page.keyboard.press('Enter')
    await expect(current()).toContainText('确认信息')
    await circles.nth(2).focus()
    await page.keyboard.press('Space')
    await expect(current()).toContainText('完成')
    await page.mouse.move(0, 0)
    const colors = await circles.nth(0).evaluate(el => ({background:getComputedStyle(el).backgroundColor, border:getComputedStyle(el).borderColor, radius:getComputedStyle(el).borderRadius}))
    expect(colors.background).not.toBe(colors.border)
    expect(colors.radius).toBe('50%')
    const bounds = await steps.boundingBox()
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  })
}

for (const width of [320, 390, 768, 1440]) {
  test(`pagination manual draft, validation and joined controls fit at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/tests/e2e/fixtures/steps-pagination.html')
    const pagination = page.locator('#pagination')
    const input = pagination.getByRole('textbox', { name: '跳转页码' })
    const apply = pagination.getByRole('button', { name: 'Apply', exact: true })
    await input.fill('2')
    await expect(page.locator('#page')).toHaveText('12')
    await input.fill('24')
    await expect(page.locator('#commits')).toHaveText('0')
    await apply.click()
    await expect(page.locator('#page')).toHaveText('24')
    await input.fill('1.5')
    await input.press('Enter')
    await expect(input).toHaveValue('1.5')
    await expect(input).toHaveAttribute('aria-invalid', 'true')
    await expect(pagination.getByRole('alert')).toContainText('1–25')
    await expect(page.locator('#commits')).toHaveText('1')
    await input.fill('3')
    await input.press('Enter')
    await expect(page.locator('#page')).toHaveText('3')
    await expect(pagination.getByRole('alert')).toHaveCount(0)
    const shape = await input.evaluate(el => {
      const wrap = el.closest('.apple-input-wrap')!, button = wrap.querySelector('button')!
      const i = el.getBoundingClientRect(), b = button.getBoundingClientRect(), css = getComputedStyle(button)
      return { gap:b.left-i.right, left:css.borderTopLeftRadius, right:css.borderTopRightRadius, parent:getComputedStyle(wrap).borderRadius }
    })
    expect(Math.abs(shape.gap)).toBeLessThan(1)
    expect(shape.left).toBe('0px')
    expect(shape.right).toBe('7px')
    expect(shape.parent).toBe('8px')
    await input.fill('99')
    await page.locator('#shrink').click()
    await expect(input).toHaveValue('3')
    await page.locator('#disable').click()
    await expect(input).toBeDisabled()
    await expect(apply).toBeDisabled()
    await expect(page.locator('#steps button').first()).toBeDisabled()
    await page.locator('#disable').click()
    await page.locator('#empty').click()
    await expect(input).toBeDisabled()
    await expect(apply).toBeDisabled()
    await expect(pagination.locator('[aria-current="page"]')).toHaveText('1')
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  })
}

test('Steps Ripple belongs only to the enabled circle, and item-disabled controls stay inert', async ({ page }) => {
  await page.goto('/tests/e2e/fixtures/steps-pagination.html')
  const steps = page.locator('#steps')
  const label = steps.locator('.apple-steps__label').first()
  await label.hover()
  await page.mouse.down()
  await expect(steps.locator('.v-ripple__container')).toHaveCount(0)
  await page.mouse.up()
  const circle = steps.locator('button.apple-steps__number').first()
  await circle.hover()
  await page.mouse.down()
  await expect(circle.locator('.v-ripple__container')).toHaveCount(1)
  await page.mouse.up()
  await expect(steps.locator('li').last().locator('button').first()).toBeDisabled()
  await expect(steps.locator('li').last().locator('button').last()).toBeDisabled()
})

test('Steps check and numeral share the circle center, with distinct completed/current/hover fills', async ({ page }) => {
  await page.setViewportSize({ width: 604, height: 900 })
  await page.goto('/tests/e2e/fixtures/steps-pagination.html')
  const circles = page.locator('#steps .apple-steps__number')
  const centerErrors = () => circles.evaluateAll(elements => elements.map(el => {
    const symbol = el.querySelector('svg') ?? el.querySelector('.apple-steps__symbol')!
    const c = el.getBoundingClientRect(), s = symbol.getBoundingClientRect()
    return { x: s.x + s.width / 2 - c.x - c.width / 2, y: s.y + s.height / 2 - c.y - c.height / 2 }
  }))
  const old = await page.addStyleTag({content: '.apple-steps__number .apple-button__content{width:auto;height:auto;line-height:1.4}.apple-steps__symbol{display:inline;min-width:0;min-height:0;line-height:normal}.apple-steps__symbol>svg{display:inline}'})
  const before = await centerErrors()
  await page.screenshot({ path: '/tmp/apptify-steps-icon-before.png' })
  await old.evaluate(el => el.remove())
  const after = await centerErrors()
  console.log('Steps symbol centers before/after', JSON.stringify({before,after}))
  for (const error of after) { expect(Math.abs(error.x)).toBeLessThan(.5); expect(Math.abs(error.y)).toBeLessThan(.5) }
  await page.mouse.move(0,0)
  const outline = await circles.first().evaluate(el=>getComputedStyle(el).backgroundColor)
  const active = await circles.nth(1).evaluate(el=>getComputedStyle(el).backgroundColor)
  expect(outline).not.toBe(active)
  await circles.first().hover()
  await expect.poll(()=>circles.first().evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(active)
  await page.mouse.move(0,0)
  await expect.poll(()=>circles.first().evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(outline)
  await page.screenshot({ path: '/tmp/apptify-steps-icon-after.png' })
})

for (const motion of ['full', 'reduced', 'none']) {
  test(`pagination shares one horizontal indicator and cleans up rapid changes with ${motion} motion`, async ({ page }) => {
    await page.goto(`/tests/e2e/fixtures/steps-pagination.html?motion=${motion}`)
    const pagination = page.locator('#pagination')
    const indicator = pagination.locator('.apple-pagination__indicator')
    const aligned = () => indicator.evaluate(el => {
      const i=el.getBoundingClientRect(), target=el.parentElement!.querySelector('[aria-current="page"]')!.getBoundingClientRect()
      return Math.abs(i.x-target.x) + Math.abs(i.y-target.y) + Math.abs(i.width-target.width) + Math.abs(i.height-target.height)
    })
    await expect(indicator).toHaveCount(1)
    await expect.poll(aligned).toBeLessThan(1)
    const duration = await page.evaluate(async () => {
      document.querySelector<HTMLButtonElement>('#pagination [aria-label="第 13 页"]')!.click()
      await new Promise(requestAnimationFrame); await new Promise(requestAnimationFrame)
      const animations=document.querySelector('#pagination .apple-pagination__indicator')!.getAnimations()
      return animations.map(animation=>Number(animation.effect!.getTiming().duration))
    })
    if (motion === 'none') expect(duration).toEqual([])
    else { expect(duration).toHaveLength(1); expect(duration[0]).toBe(motion === 'reduced' ? 80 : 300) }
    for (const label of ['上一页','下一页','上一页','下一页']) await pagination.getByRole('button',{name:label,exact:true}).click()
    await pagination.getByRole('textbox',{name:'跳转页码'}).fill('25')
    await pagination.getByRole('button',{name:'Apply',exact:true}).click()
    await expect.poll(aligned).toBeLessThan(1)
    await expect.poll(()=>indicator.evaluate(el=>el.getAnimations().length)).toBe(0)
    await pagination.getByRole('textbox',{name:'跳转页码'}).fill('2')
    await pagination.getByRole('textbox',{name:'跳转页码'}).press('Enter')
    await expect.poll(aligned).toBeLessThan(1)
    await page.locator('#shrink').click()
    await expect(pagination.locator('.apple-pagination__indicator')).toHaveCount(1)
    await expect.poll(aligned).toBeLessThan(1)
    await page.locator('#empty').click()
    await expect.poll(aligned).toBeLessThan(1)
    await expect.poll(()=>indicator.evaluate(el=>el.getAnimations().length)).toBe(0)
  })
}

test('switching global motion off cancels a running pagination indicator', async ({page})=>{
  await page.goto('/tests/e2e/fixtures/steps-pagination.html')
  const indicator=page.locator('#pagination .apple-pagination__indicator')
  await expect(indicator).toBeVisible()
  await page.locator('#pagination [aria-label="第 13 页"]').click()
  await page.locator('#motion-none').click()
  await expect.poll(()=>indicator.evaluate(el=>el.getAnimations().length)).toBe(0)
})

test('narrow pagination preserves 44px square targets by reducing pages and keeps its indicator aligned', async ({page}) => {
  await page.setViewportSize({width:320,height:900})
  await page.goto('/components#apple-pagination')
  const demo = page.locator('#apple-pagination .component-demo')
  const pagination = demo.locator('.apple-pagination')
  const track = pagination.locator('.apple-pagination__pages')
  const input = pagination.getByRole('textbox',{name:'跳转页码'})
  for (const pageNumber of [1,2,6,12,3]) {
    await input.fill(String(pageNumber))
    await input.press('Enter')
    await expect(track.locator('[aria-current="page"]')).toHaveText(String(pageNumber))
    await expect.poll(() => track.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
    const bounds = await demo.boundingBox()
    for (const button of await track.locator(':scope > button').all()) {
      const rect = (await button.boundingBox())!
      expect(rect.width).toBeCloseTo(44,3)
      expect(rect.height).toBeCloseTo(44,3)
      expect(rect.x).toBeGreaterThanOrEqual(bounds!.x)
      expect(rect.x + rect.width).toBeLessThanOrEqual(bounds!.x + bounds!.width + .1)
    }
    await expect.poll(() => track.locator('.apple-pagination__indicator').evaluate(el => {
      const a=el.getBoundingClientRect(), b=el.parentElement!.querySelector('[aria-current="page"]')!.getBoundingClientRect()
      return Math.abs(a.x-b.x)+Math.abs(a.width-b.width)
    })).toBeLessThan(1)
  }
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
})
