import { expect, test } from '@playwright/test'

for (const hasTouch of [false, true]) {
  test.describe(`unified images with touch=${hasTouch}`, () => {
    test.use({ hasTouch })
    test('orientation controls and optional titles survive resizing the same preview', async ({ page }) => {
      await page.setViewportSize({ width: 1280, height: 720 })
      await page.goto('/tests/e2e/fixtures/mobile-images.html')
      await page.locator('#compact .apple-image__trigger').first().click()
      const viewer = page.getByRole('dialog', { name: '图片预览', exact: true })
      await expect(viewer).toHaveAttribute('data-phase', 'open')
      await expect(viewer.getByRole('button', { name: '关闭图片预览', exact: true })).toBeVisible()
      await expect(viewer.getByRole('button', { name: '下一张', exact: true })).toBeVisible()
      await expect(viewer.locator('.apple-viewer-title')).toHaveCount(0)
      await expect(viewer.locator('.apple-viewer-caption button')).toHaveCount(4)
      const original = await viewer.elementHandle()
      await page.setViewportSize({ width: 390, height: 844 })
      await expect(viewer.getByRole('button', { name: '关闭图片预览', exact: true })).toHaveCount(0)
      await expect(viewer.getByRole('button', { name: '下一张', exact: true })).toHaveCount(0)
      await expect(viewer.getByRole('button', { name: '缩小', exact: true })).toHaveCount(0)
      await expect(viewer.getByRole('button', { name: '放大', exact: true })).toHaveCount(0)
      await expect(page.locator('#compact .apple-image__arrows')).toHaveCount(0)
      await expect(viewer.locator('.apple-viewer-caption button')).toHaveCount(2)
      expect(await original!.evaluate(element => element === document.querySelector('.apple-image-viewer'))).toBe(true)
      await viewer.getByRole('button', { name: '向右旋转90度', exact: true }).click()
      await expect(viewer).toHaveAttribute('data-phase', 'open')
      await expect(viewer.locator('.apple-viewer-image')).toHaveCSS('transform', 'matrix(0, 1, -1, 0, 0, 0)')
      const photo = await viewer.locator('.apple-viewer-image').boundingBox()
      expect(photo!.width).toBeCloseTo(390, 0)
      expect(photo!.height).toBeCloseTo(585, 0)
      await page.keyboard.press('Escape')
      await expect(viewer).toHaveCount(0)
      await expect(page.locator('#compact .apple-image__trigger img').first()).toHaveCSS('opacity', '1')
      expect(await page.evaluate(() => document.body.style.overflow)).toBe('')
    })
  })
}

test('one capsule orders rotation, zoom and optional name; rotations belong to each image', async ({ page }) => {
  await page.goto('/tests/e2e/fixtures/image-carousel.html')
  await page.locator('#photos .apple-image__trigger').first().click()
  const viewer = page.getByRole('dialog', { name: '图片预览', exact: true })
  await expect(viewer).toHaveAttribute('data-phase', 'open')
  await expect(viewer.locator('.apple-viewer-caption')).toHaveCount(1)
  expect(await viewer.locator('.apple-viewer-caption > *').evaluateAll(elements => elements.map(element => element.getAttribute('aria-label') || element.textContent))).toEqual(['向左旋转90度', '缩小', '山间清晨', '放大', '向右旋转90度'])
  await viewer.getByRole('button', { name: '向左旋转90度', exact: true }).click()
  await expect(viewer).toHaveAttribute('data-phase', 'open')
  await expect(viewer.locator('.apple-viewer-image')).toHaveCSS('transform', 'matrix(0, -1, 1, 0, 0, 0)')
  await viewer.getByRole('button', { name: '下一张', exact: true }).click()
  await expect(viewer).toHaveAttribute('data-phase', 'open')
  await expect(viewer.locator('.apple-viewer-title')).toHaveText('一场聆听')
  await expect(viewer.locator('.apple-viewer-image')).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 0)')
  await viewer.getByRole('button', { name: '上一张', exact: true }).click()
  await expect(viewer).toHaveAttribute('data-phase', 'open')
  await expect(viewer.locator('.apple-viewer-image')).toHaveCSS('transform', 'matrix(0, -1, 1, 0, 0, 0)')
  await viewer.getByRole('button', { name: '放大', exact: true }).click()
  await expect(viewer).toHaveAttribute('data-phase', 'open')
  expect(Number(await viewer.getAttribute('data-scale'))).toBeGreaterThan(1)
  await page.screenshot({ path: 'test-results/unified-image-capsule.png' })
  await viewer.getByRole('button', { name: '关闭图片预览', exact: true }).click()
  await expect(viewer).toHaveCount(0)
})

test('carousel arrows align with the picture and hover uses the card shadow', async ({ page }) => {
  await page.goto('/tests/e2e/fixtures/image-carousel.html')
  const photos = page.locator('#photos')
  await photos.hover()
  await expect(photos.locator('.apple-image__surface')).toHaveCSS('transform', 'matrix(1.04, 0, 0, 1.04, 0, 0)')
  await expect(photos.locator('.apple-image__surface')).toHaveCSS('box-shadow', 'rgba(0, 0, 0, 0.16) 2px 4px 16px 0px')
  const picture = await photos.locator('.apple-image__slide-picture').first().boundingBox()
  const arrow = await photos.getByRole('button', { name: '下一张图片', exact: true }).boundingBox()
  expect(Math.abs(picture!.y + picture!.height / 2 - arrow!.y - arrow!.height / 2)).toBeLessThan(1)
})

test('carousel starts automatically every five seconds and loops', async ({ page }) => {
  await page.clock.install()
  await page.goto('/tests/e2e/fixtures/image-carousel.html')
  await page.locator('#none').click()
  await page.mouse.move(0, 0)
  const photos = page.locator('#photos')
  await expect(photos).toHaveAttribute('data-index', '0')
  for (const index of [1, 2, 3, 0]) {
    await page.clock.runFor(5000)
    await expect(photos).toHaveAttribute('data-index', String(index))
  }
})
