import { componentMetadata } from './editor/component-metadata'
export interface CatalogItem { name: string; label: string; group: string; description: string; api: string; code: string }
const item = (name: string, api: string, code: string): CatalogItem => ({ name, ...componentMetadata[name], api, code })
export const catalog: CatalogItem[] = [
  item('AppleButton', 'variant · size · icon · iconOnly · label · loading · disabled · ripple · motion', '<apple-button variant="primary" :loading="saving" @click="save">继续</apple-button>'),
  item('AppleLink', 'href · external · disabled | slot: default', '<apple-link href="https://www.apple.com.cn/" external>Apple 官网</apple-link>'),
  item('AppleSearch', 'v-model(string) · label · placeholder · disabled | search(query)', '<apple-search v-model="query" label="搜索设置" placeholder="搜索设置" @search="search" />'),
  item('AppleProvider', 'theme · motion(auto|full|reduced|none) | slot: default', '<apple-provider theme="dark" motion="auto">\n  <apple-button>继续</apple-button>\n</apple-provider>'),
  item('AppleOverlayHost', '由 AppleProvider 自动包含；无公开 props、事件或插槽', '<apple-overlay-host />'),
  item('AppleContainer', 'width(number|string) | slot: default', '<apple-container :width="960">\n  <apple-stack>内容</apple-stack>\n</apple-container>'),
  item('AppleStack', 'direction(row|column) · gap · align · wrap | slot: default', '<apple-stack direction="row" :gap="16" align="center">\n  <apple-button>继续</apple-button>\n  <apple-button variant="secondary">取消</apple-button>\n</apple-stack>'),
  item('AppleGrid', 'min(number) · gap(number) | slot: default', '<apple-grid :min="240" :gap="20">\n  <div v-for="item in items" :key="item.id">{{ item.label }}</div>\n</apple-grid>'),
  item('AppleCard', 'title · subtitle · text · image · zoom · shadow · motion | slots: media, title, icon, actions', '<apple-card title="AirPods Max" subtitle="声音，出类拔萃。" motion="auto">\n  <template #actions><apple-button>进一步了解</apple-button></template>\n</apple-card>'),
  item('AppleImage', 'gallery(object|array) · index · preview · carousel · disabled · label · galleryLayout(compact|tiled|tiled-wrap) · v-model:index | item({item,index,active}) · squared · aspectRatio · fit', '<apple-image :gallery="images" gallery-layout="compact" :index="0" />'),
  item('AppleAvatar', 'src · name · size', '<apple-avatar name="林初" :size="48" />'),
  item('AppleAvatarGroup', 'items[{name,src,value}] · max · size · label | slot: default', '<apple-avatar-group :items="members" :max="4" :size="40" label="项目成员" />'),
  item('AppleBadge', 'value · max · dot · tone', '<apple-badge :value="8"><apple-button>消息</apple-button></apple-badge>'),
  item('AppleTag', 'tone · closable | close', '<apple-tag tone="success" closable @close="remove">已完成</apple-tag>'),
  item('AppleDivider', 'label · vertical', '<apple-divider label="更多选择" />'),
  item('AppleInput', 'v-model · label · placeholder · type · error · hint · clearable · disabled', '<apple-input v-model="name" label="姓名" placeholder="怎么称呼你" clearable />'),
  item('AppleTextarea', 'v-model · label · rows · maxlength · error · hint', '<apple-textarea v-model="bio" label="个人简介" :maxlength="160" />'),
  item('AppleSelect', 'v-model · label · items[{label,value,disabled}] · placeholder · disabled', '<apple-select v-model="city" label="所在城市" :items="cities" />'),
  item('AppleAutocomplete', 'v-model · label · items · placeholder · disabled', '<apple-autocomplete v-model="device" label="搜索设备" :items="devices" />'),
  item('AppleCheckbox', 'v-model · label · disabled · indeterminate', '<apple-checkbox v-model="agreed" label="我已阅读并同意条款" />'),
  item('AppleRadioGroup', 'v-model · label · items · disabled', '<apple-radio-group v-model="delivery" label="配送方式" :items="methods" />'),
  item('AppleSwitch', 'v-model · label · disabled', '<apple-switch v-model="notifications" label="接收通知" />'),
  item('AppleSlider', 'v-model · label · min · max · step · disabled', '<apple-slider v-model="volume" label="音量" :min="0" :max="100" />'),
  item('AppleStepper', 'v-model · label · min · max · step', '<apple-stepper v-model="quantity" label="数量" :min="1" :max="10" />'),
  item('AppleSegmentedControl', 'v-model · items · label · disabled', '<apple-segmented-control v-model="period" :items="periods" label="统计周期" />'),
  item('AppleDatePicker', 'v-model · format · granularity · label · min · max · required · disabled | change(value)', '<apple-date-picker v-model="date" label="到店日期" format="YYYY/MM/DD HH:mm" />'),
  item('AppleColorPicker', 'v-model(#hex) · label · disabled', '<apple-color-picker v-model="color" label="强调色" />'),
  item('AppleUpload', 'v-model(File[]) · label · accept · multiple · maxSize(bytes) · maxFiles · capture | reject([{file,reason}]), remove(file)', '<apple-upload v-model="files" label="上传图片" accept="image/*" multiple :max-files="5" />'),
  item('AppleOtpInput', 'v-model · length · label | complete', '<apple-otp-input v-model="code" :length="6" label="验证码" />'),
  item('AppleCascader', 'v-model(value[]) · items[{label,value,children}] · label', '<apple-cascader v-model="region" label="所在地区" :items="regions" />'),
  item('AppleRate', 'v-model · max · label · readonly · disabled', '<apple-rate v-model="rating" label="体验评分" />'),
  item('AppleForm', 'validator(FormData) => boolean|string|Promise · loading · disabled | submit(FormData), invalid, reset | methods: validate(), submit(), reset()', '<apple-form :validator="validate" @submit="submit">\n  <apple-input v-model="name" name="name" label="姓名" required />\n  <apple-button type="submit">提交</apple-button>\n</apple-form>'),
  item('AppleFormField', 'label · for · error · hint · required · disabled | default({id,disabled,required,aria-invalid,aria-describedby})', '<apple-form-field label="个人网站" :error="error">\n  <template #default="field">\n    <input v-bind="field" v-model="website" class="apple-control" type="url" />\n  </template>\n</apple-form-field>'),
  item('AppleNavibar', 'v-model · items · brand · brandHref · fixed · breakpoint=640 · hideOnPreview · label · motion | change(value,item), toggle(open) | slots: brand, item, actions', '<apple-navibar v-model="page" brand="Apptify" :items="pages" />'),
  item('AppleAside', 'hideOnPreview=true · motion | slot: default | 布局由调用方提供', '<apple-aside :hide-on-preview="false">\n  <apple-list :items="items" />\n</apple-aside>'),
  item('AppleTabs', 'v-model · items[{label,value,disabled}] | slot: default({value})', '<apple-tabs v-model="tab" :items="tabs">\n  <template #default="{ value }">{{ value }}</template>\n</apple-tabs>'),
  item('AppleTabBar', 'v-model · items · label · disabled · motion | slot: default({value})', '<apple-tab-bar v-model="tab" :items="tabs">\n  <template #default="{value}">{{ value }}</template>\n</apple-tab-bar>'),
  item('AppleBreadcrumbs', 'items[{label,value,href,disabled}] · label', '<apple-breadcrumbs :items="[{label:\'首页\',value:\'home\',href:\'/\'},{label:\'设置\',value:\'settings\'}]" />'),
  item('ApplePagination', 'v-model(page) · total · pageSize', '<apple-pagination v-model="page" :total="120" :page-size="10" />'),
  item('AppleSteps', 'v-model(index) · items[{label,value,description,disabled}] · clickable · disabled', '<apple-steps v-model="step" :items="steps" clickable />'),
  item('AppleAccordion', 'v-model · items[{label,value,content}] · multiple', '<apple-accordion :items="questions" />'),
  item('AppleTable', 'columns[{key,label,sortable,width,minWidth,maxWidth}] · rows · rowKey · selectable · pageSize · virtual · height · rowHeight · overscan · resizable | update:selected, column-resize', '<apple-table :columns="columns" :rows="rows" row-key="id" virtual :height="360" :row-height="48" />'),
  item('AppleTree', 'v-model · items[{label,value,children}] | select', '<apple-tree v-model="selected" :items="folders" />'),
  item('AppleList', 'v-model · items[{label,value,description,href,disabled}] · selectable | select(item)', '<apple-list v-model="setting" :items="settings" selectable @select="openSetting" />'),
  item('AppleTimeline', 'items[{label,value,description,time,tone}] · orientation(horizontal|vertical) · label', '<apple-timeline :items="events" orientation="horizontal" />'),
  item('AppleStatistic', 'label · value · prefix · suffix · precision', '<apple-statistic label="本月访问" :value="12840" suffix="次" />'),
  item('AppleDialog', 'v-model · title · persistent · confirmText · cancelText | confirm, cancel', '<apple-dialog v-model="open" title="保存更改？" @confirm="save">\n  你的更改会同步到所有设备。\n</apple-dialog>'),
  item('AppleDrawer', 'v-model · title · placement(left|right|bottom) · width · persistent · loading', '<apple-drawer v-model="open" title="偏好设置" placement="right">内容</apple-drawer>'),
  item('AppleSheet', 'v-model · title · persistent', '<apple-sheet v-model="open" title="分享">内容</apple-sheet>'),
  item('AppleSnackbar', 'v-model · message · title · tone · duration(ms) · action · closable | close, action', "const notice = apple.notify('已保存', { tone: 'success', duration: 4000 })"),
  item('AppleAlert', 'v-model · title · message · tone · closable | close', '<apple-alert v-model="visible" title="一切已就绪" tone="success" closable>内容已同步。</apple-alert>'),
  item('AppleProgress', 'modelValue · max · label · indeterminate · showValue · tone', '<apple-progress :model-value="68" label="正在上传" show-value />'),
  item('AppleSpinner', 'size · label', '<apple-spinner label="正在加载" />'),
  item('AppleSkeleton', 'variant(text|avatar|card|list|table|image) · lines · rows · columns · avatar · width · height · animated · label · motion', '<apple-skeleton variant="list" :rows="3" avatar />'),
  item('AppleEmpty', 'title · description | slot: default', '<apple-empty title="还没有收藏" description="喜欢的内容，会出现在这里。" />'),
  item('ApplePopover', 'v-model · label · placement · align · width · disabled | activator({props,open,close,isOpen}), default({close})', '<apple-popover label="更多选项">\n  <template #activator><apple-button variant="secondary">更多</apple-button></template>\n  <apple-switch v-model="sync" label="自动同步" />\n</apple-popover>'),
  item('AppleTooltip', 'text | slot: default', '<apple-tooltip text="添加到收藏"><apple-button>收藏</apple-button></apple-tooltip>'),
  item('AppleMenu', 'v-model · items[{label,value,disabled,danger,icon,description}] · label · selected | select(value,item)', '<apple-menu :items="actions" label="更多操作" @select="onAction" />'),
  item('AppleActionSheet', 'v-model · title · message · items[{label,value,disabled,danger}] · cancelText | default slot {select(item),close(value)} | select(value,item)', '<apple-action-sheet v-model="open" title="选择操作" @select="onAction">\n  <template #default="{ select }">\n    <apple-button @click="select({ label: \'收藏\', value: \'favorite\' })">加入收藏</apple-button>\n  </template>\n</apple-action-sheet>'),
  item('ApplePullRefresh', 'v-model(refreshing) · threshold · label · disabled | refresh(done)', '<apple-pull-refresh @refresh="async done => { await reload(); done() }">内容</apple-pull-refresh>'),
  item('AppleBackTop', 'threshold · label', '<apple-back-top :threshold="400" />'),
  item('AppleFloatingGroup', 'backTop · threshold · target · label · motion | default', '<apple-floating-group :threshold="300" />'),
  item('AppleAutoSize', 'axis(height|both) · motion | default', '<apple-auto-size><div v-if="expanded">详情内容</div></apple-auto-size>'),
  item('AppleTransition', 'name(page|slide-x|slide-y|fade) · mode · appear · motion | default', '<apple-transition name="page"><router-view /></apple-transition>'),
  item('AppleInfiniteScroll', 'loading · finished · error · disabled · distance | load(done), retry(done)', '<apple-infinite-scroll :finished="finished" @load="async done => { await loadMore(); done() }">内容</apple-infinite-scroll>'),
]
export const groups = ['全部组件', '基础', '表单', '导航', '数据展示', '反馈', '移动交互']

export const componentId = (name: string) => name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
export const sections = [
  { id: 'basics', label: '基础' },
  { id: 'forms', label: '表单' },
  { id: 'navigation', label: '导航' },
  { id: 'data', label: '数据展示' },
  { id: 'feedback', label: '反馈' },
  { id: 'mobile', label: '移动交互' },
].map(section => ({ ...section, items: catalog.filter(item => item.group === section.label) }))
